"""initial schema

Revision ID: 83e5f2d026f7
Revises: 
Create Date: 2026-06-23 17:03:12.387311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e5f2d026f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('land_area_acres', sa.Float(), nullable=True),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('theme_preference', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('recommendation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nitrogen', sa.Float(), nullable=False),
    sa.Column('phosphorus', sa.Float(), nullable=False),
    sa.Column('potassium', sa.Float(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('rainfall', sa.Float(), nullable=False),
    sa.Column('weather_source', sa.String(length=20), nullable=False),
    sa.Column('predicted_crop', sa.String(length=50), nullable=False),
    sa.Column('top5_json', sa.JSON(), nullable=False),
    sa.Column('shap_explanation_json', sa.JSON(), nullable=True),
    sa.Column('model_used', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_history_user_id'), ['user_id'], unique=False)

    op.create_table('saved_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.Column('plan_name', sa.String(length=120), nullable=False),
    sa.Column('total_land_acres', sa.Float(), nullable=False),
    sa.Column('allocations_json', sa.JSON(), nullable=False),
    sa.Column('allocation_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['recommendation_history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_plans_history_id'), ['history_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_plans_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_plans_history_id'))

    op.drop_table('saved_plans')
    with op.batch_alter_table('recommendation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_history_created_at'))

    op.drop_table('recommendation_history')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
